# On part d'une image Node.js déjà présente en local dans Docker.
FROM n8nio/n8n:latest
ENTRYPOINT []

# On définit le dossier de travail dans le conteneur
WORKDIR /app

USER root

# On copie les fichiers de configuration (package.json)
COPY package*.json ./

# On installe les dépendances
RUN npm ci --include=dev

# On copie tout le reste du code source
COPY . .

# On compile le TypeScript en JavaScript
RUN npm run build

# L'API écoutera sur le port 3000 [cite: 185]
EXPOSE 3000

# On lance l'application
CMD ["npm", "start"]