FROM n8nio/n8n:latest
ENTRYPOINT []

WORKDIR /app

USER root

COPY package*.json ./

RUN npm ci --include=dev

COPY . .

RUN npm run build

EXPOSE 80

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "80"]
